In [4]:
!pip3 install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (89 kB)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp312-cp312-macosx_11_0_arm64.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 24.0 MB/s eta 0:00:00a 0:00:01
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2024.2

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip3 install --upgrade pip

In [1]:
import pandas as pd

In [6]:
stops = pd.read_csv('data/stops.txt', delimiter = ",")
routes = pd.read_csv('data/routes.txt', delimiter = ",")
trips = pd.read_csv('data/trips.txt', delimiter = ",")
stop_times = pd.read_csv('data/stop_times.txt', delimiter = ",")
trips

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1
1,6612,1,13997546,2 Macdonald/To Burrard Station,NaN,0,2099318.0,292023,0,1
2,6612,1,13997547,2 Macdonald/To Burrard Station,NaN,0,2099321.0,292023,0,1
3,6612,1,13997548,2 Macdonald/To Burrard Station,NaN,0,2099322.0,292023,0,1
4,6612,1,13997549,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1
...,...,...,...,...,...,...,...,...,...,...
60992,31822,1,14321214,741 Anderson Creek,NaN,0,2123239.0,293067,0,1
60993,31822,1,14321215,741 Haney Place,NaN,1,2123239.0,293070,0,1
60994,6651,101,14321448,130 Willingdon/To Metrotown Station,NaN,1,2107629.0,294477,0,1
60995,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1
60996,HD,-999,48441,NaN,NaN,0,NaN,4484,2,0

In [9]:
# firstly merge trips with stop_times  
merged_df = pd.merge(trips, stop_times, on='trip_id')  

# then merge the result with stops  
merged_df = pd.merge(merged_df, stops, on='stop_id')  
merged_df

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,...,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,wheelchair_boarding
0,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1,...,50640.0,Dunbar Loop @ Bay 2,NaN,49.234661,-123.185757,BUS ZN,NaN,0,NaN,1
1,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1,...,51267.0,Northbound Macdonald St @ Oliver Cres,NaN,49.249455,-123.167732,BUS ZN,NaN,0,NaN,1
2,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1,...,51269.0,Northbound Macdonald St @ W 22 Ave,NaN,49.253089,-123.167687,BUS ZN,NaN,0,NaN,1
3,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1,...,50056.0,Northbound Macdonald St @ W 16 Ave,NaN,49.258079,-123.168299,BUS ZN,NaN,0,NaN,1
4,6612,1,13997545,2 Macdonald/To Burrard Station,NaN,0,2099312.0,292023,0,1,...,60359.0,Northbound Macdonald St @ W 13 Ave,NaN,49.260303,-123.168238,BUS ZN,NaN,0,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1780384,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1,...,52503.0,Northbound Nelson Ave @ Newton St,NaN,49.227326,-122.994102,BUS ZN,NaN,0,NaN,1
1780385,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1,...,52504.0,Northbound Nelson Ave @ Dover St,NaN,49.230297,-122.994120,BUS ZN,NaN,0,NaN,1
1780386,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1,...,52505.0,Northbound Nelson Ave @ Grafton St,NaN,49.232104,-122.994135,BUS ZN,NaN,0,NaN,1
1780387,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1,...,52506.0,Northbound Nelson Ave @ Sardis Cres,NaN,49.233648,-122.994145,BUS ZN,NaN,0,NaN,2
1780388,6646,201,14321449,110 Lougheed Station,NaN,0,2107629.0,292358,0,1,...,52507.0,Westbound Bond St @ Nelson Ave,NaN,49.235465,-122.994807,BUS ZN,NaN,0,NaN,1

In [24]:
# filter the dataframe by route_id  
filtered_df = merged_df[(merged_df['route_id'] == "37810") & (merged_df['direction_id'] == 0)]
filtered_df

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,...,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,wheelchair_boarding
1534463,37810,1,14057112,R4 41ST Avenue/To Joyce Station,NaN,0,2103105.0,293231,0,1,...,60162.0,UBC Exchange @ Bay 4,NaN,49.267040,-123.247902,BUS ZN,NaN,0,NaN,1
1534464,37810,1,14057112,R4 41ST Avenue/To Joyce Station,NaN,0,2103105.0,293231,0,1,...,50253.0,Eastbound E 41 Ave @ Main St,NaN,49.232967,-123.101913,BUS ZN,NaN,0,NaN,1
1534465,37810,1,14057112,R4 41ST Avenue/To Joyce Station,NaN,0,2103105.0,293231,0,1,...,61503.0,Eastbound E 41 Ave @ Fraser St,NaN,49.232781,-123.090946,BUS ZN,NaN,0,NaN,1
1534466,37810,1,14057112,R4 41ST Avenue/To Joyce Station,NaN,0,2103105.0,293231,0,1,...,50649.0,Eastbound E 41 Ave @ Knight St,NaN,49.232598,-123.076419,BUS ZN,NaN,0,NaN,1
1534467,37810,1,14057112,R4 41ST Avenue/To Joyce Station,NaN,0,2103105.0,293231,0,1,...,51121.0,Eastbound E 41 Ave @ Victoria Dr,NaN,49.232713,-123.065050,BUS ZN,NaN,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677167,37810,1,14126955,R4 41ST Avenue/To Joyce Station,NaN,0,2103136.0,293231,0,1,...,50377.0,Eastbound W 41 Ave @ Carnarvon St,NaN,49.234677,-123.172505,BUS ZN,NaN,0,NaN,1
1677168,37810,1,14126955,R4 41ST Avenue/To Joyce Station,NaN,0,2103136.0,293231,0,1,...,60386.0,Eastbound W 41 Ave @ East Blvd,NaN,49.234484,-123.154358,BUS ZN,NaN,0,NaN,1
1677169,37810,1,14126955,R4 41ST Avenue/To Joyce Station,NaN,0,2103136.0,293231,0,1,...,50199.0,Eastbound W 41 Ave @ Granville St,NaN,49.234220,-123.138484,BUS ZN,NaN,0,NaN,1
1677170,37810,1,14126955,R4 41ST Avenue/To Joyce Station,NaN,0,2103136.0,293231,0,1,...,50804.0,Eastbound W 41 Ave @ Oak St,NaN,49.233800,-123.126888,BUS ZN,NaN,0,NaN,1
1677171,37810,1,14126955,R4 41ST Avenue/To Joyce Station,NaN,0,2103136.0,293231,0,1,...,60349.0,Oakridge-41st Ave Station @ Bay 3,NaN,49.233373,-123.114517,BUS ZN,NaN,0,NaN,1

In [26]:
# get distinct values  
distinct_values = filtered_df[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']].drop_duplicates()
distinct_values

,stop_id,stop_name,stop_lat,stop_lon
1534463,12361,UBC Exchange @ Bay 4,49.267040,-123.247902
1534464,255,Eastbound E 41 Ave @ Main St,49.232967,-123.101913
1534465,12134,Eastbound E 41 Ave @ Fraser St,49.232781,-123.090946
1534466,655,Eastbound E 41 Ave @ Knight St,49.232598,-123.076419
1534467,1130,Eastbound E 41 Ave @ Victoria Dr,49.232713,-123.065050
1534468,1133,Eastbound E 41 Ave @ Clarendon St,49.232754,-123.054813
1534469,1137,Eastbound E 41 Ave @ Rupert St,49.232880,-123.042556
1534470,1648,Northbound Joyce St @ Kingsway,49.234391,-123.035520
1534471,1736,Joyce Station @ Bay 1 Unload Only,49.238592,-123.032425
1534472,12652,Southbound Wesbrook Mall @ Agronomy Rd,49.263690,-123.243491
1534473,1896,Westbound W 16 Ave @ Wesbrook Mall,49.254822,-123.239452
1534474,12625,Dunbar Loop @ Bay 7,49.234694,-123.184268
1534475,381,Eastbound W 41 Ave @ Carnarvon St,49.234677,-123.172505
1534476,12631,Eastbound W 41 Ave @ East Blvd,49.234484,-123.154358
1534477,199,Eastbound W 41 Ave @ Granville St,49.234220,-123.138484
1534478,811,Eastbound W 41 Ave @ Oak St,49.233800,-123.126888
1534479,12586,Oakridge-41st Ave Station @ Bay 3,49.233373,-123.114517